### ISSUE TITLE
Bug: ignore-pattern not followed in sort-objects

### ISSUE THREAD

**Issue by ArthurGuez** [azat-io/eslint-plugin-perfectionist#104]
### Describe the bug

Hi there,

I'm using Panda CSS to write my CSS and use an object syntax.

I'd like `sort-objects` to ignore those objects since I have my own way of sorting them.
However, using the options provided (`ignore-pattern` and/or `styled-components`) doesn't work as expected.

### Code example

My class : 

`const headerClass = css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '3',
    gridGap: '8',
  });`
  
  My rule config : 
  
  `"perfectionist/sort-objects": [
      "error",
      {
        "ignore-pattern": ["*Class"],
        "styled-components": false
      }
    ],`

Having `"styled-components": true` makes no difference

### ESLint version

v8.56.0

### ESLint Plugin Perfectionist version

v2.5.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Thank you for your issue!

This bug was implemented in d4e80116cdc89dee358b1e527265e6648f8bfc56 and released in [v3.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.0.0).

If you'd like, you can support the release with a retweet:
https://x.com/azat_io_en/status/1815367279191761054
