### ISSUE TITLE
Feature: support Astro and/or Vue

### ISSUE THREAD

**Issue by jochemkeller** [azat-io/eslint-plugin-perfectionist#25]
### Describe the rule

Hi, thanks for creating this awesome plug-in! I've recently incorporated it into my own opinionated ruleset here: [@zeebats/eslint-config](https://github.com/zeebats/eslint-config/blob/feature/1.4.0/rules/plugins/perfectionist.js) and I'm looking to release that version soon 🚀 should be a nice drop-in for others to get an opinionated eslint-config ready to go.

I noticed while testing in an Astro × Vue project that for these filetypes, this plug-in doesn't work. This is of course due to what you mention in your [introduction](https://eslint-plugin-perfectionist.azat.io/guide/introduction#introduction):

> The plugin supports:
>
> • JavaScript
> • TypeScript
> • JSX

However I think these would be nice additions! And I would like to contribute in making this a reality :-) 
Could you point me in the right direction? It is my understanding that for both these filetypes there are already parsers available: [Astro](https://github.com/ota-meshi/astro-eslint-parser) & [Vue](https://github.com/vuejs/vue-eslint-parser). So maybe it is pretty easy to hook into these?

### Code example

None at this time, please let me know if you require more information

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Sounds like a good idea. I love Vue.

The plugin currently uses the [ESLint parser for TypeScript](https://github.com/typescript-eslint/typescript-eslint). It works with JSX, for which reason we maintain rules for sorting React's props.

In order to work with Vue/Astro/Svelte, we will have to install third-party parsers:

* [vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser)
* [astro-eslint-parser](https://github.com/ota-meshi/astro-eslint-parser)
* [svelte-eslint-parser](https://github.com/sveltejs/svelte-eslint-parser)

I would like to have as few dependencies as possible.

I need to think about how this can be implemented.

**Comment by azat-io** [comment]
Will be implemented in v2.0.0 (#32)

**Comment by azat-io** [comment]
Added in 036b41d6a1a3efd4f20477d45a448ef3d4520a17, e0312754c3fb54db9f2c8e9e50340eed24b5b69a and 409295e73782f131b292f1ef8e570fe466764e14.

Release is coming soon.

**Comment by azat-io** [comment]
Released in [v2.0.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v2.0.0)

**Comment by jochemkeller** [comment]
Amazing @azat-io! Thanks a ton for all your hard work 🙏🚀
